/**
 * Enlaces a búsquedas de Idealista (no anuncios concretos).
 * Rutas comprobadas para Baixo Miño; ampliar el mapa al añadir fichas.
 */

const VENTA = "https://www.idealista.com/venta-viviendas";

/** Slug Idealista por slug interno de ficha. */
const MUNICIPIO_PATH: Record<string, string> = {
  "a-guarda": "a-guarda-pontevedra",
  oia: "oia-pontevedra",
  "o-rosal": "o-rosal-pontevedra",
  tomino: "tomino-pontevedra",
  tui: "tui-pontevedra",
  baiona: "baiona-pontevedra",
  nigran: "nigran-pontevedra",
  gondomar: "gondomar-pontevedra",
  vigo: "vigo-pontevedra",
  redondela: "redondela-pontevedra",
  soutomaior: "soutomaior-pontevedra",
  vilaboa: "vilaboa-pontevedra",
  cangas: "cangas-pontevedra",
  moana: "moana-pontevedra",
  bueu: "bueu-pontevedra",
  marin: "marin-pontevedra",
  pontevedra: "pontevedra-pontevedra",
  poio: "poio-pontevedra",
  sanxenxo: "sanxenxo-pontevedra",
  "o-grove": "o-grove-pontevedra",
  meano: "meano-pontevedra",
  cambados: "cambados-pontevedra",
  "a-illa-de-arousa": "illa-de-arousa-pontevedra",
  "vilanova-de-arousa": "vilanova-de-arousa-pontevedra",
  "vilagarcia-de-arousa": "vilagarcia-de-arousa-pontevedra",
  rianxo: "rianxo-a-coruna",
  boiro: "boiro-a-coruna",
  "a-pobra-do-caraminal": "a-pobra-do-caraminal-a-coruna",
  ribeira: "ribeira-a-coruna",
  "porto-do-son": "porto-do-son-a-coruna",
  noia: "noia-a-coruna",
  "a-coruna": "a-coruna-a-coruna",
  oleiros: "oleiros-a-coruna",
  sada: "sada-a-coruna",
  bergondo: "bergondo-a-coruna",
  mino: "mino-a-coruna",
  ares: "ares-a-coruna",
  ferrol: "ferrol-a-coruna",
  "o-vicedo": "o-vicedo-lugo",
  viveiro: "viveiro-lugo",
  xove: "xove-lugo",
  cervo: "cervo-lugo",
  burela: "burela-lugo",
  foz: "foz-lugo",
  barreiros: "barreiros-lugo",
  ribadeo: "ribadeo-lugo",
  castropol: "castropol-asturias",
  "tapia-de-casariego": "tapia-de-casariego-asturias",
  navia: "navia-asturias",
  "luarca-valdes": "luarca-asturias",
  cudillero: "cudillero-asturias",
  "muros-de-nalon": "muros-de-nalon-asturias",
  "soto-del-barco": "soto-del-barco-asturias",
  "salinas-castrillon": "salinas-asturias",
  "luanco-gozon": "luanco-asturias",
  "candas-carreno": "candas-asturias",
  gijon: "gijon-asturias",
  villaviciosa: "villaviciosa-asturias",
  colunga: "colunga-asturias",
  ribadesella: "ribadesella-asturias",
  llanes: "llanes-asturias",
  ribadedeva: "ribadedeva-asturias",
  "san-vicente-de-la-barquera": "san-vicente-de-la-barquera-cantabria",
  comillas: "comillas-cantabria",
  suances: "suances-cantabria",
  "liencres-pielagos": "liencres-cantabria",
  santander: "santander-cantabria",
  "ribamontan-al-mar": "ribamontan-al-mar-cantabria",
  noja: "noja-cantabria",
  santona: "santona-cantabria",
  laredo: "laredo-cantabria",
  "castro-urdiales": "castro-urdiales-cantabria",
  valenca: "valenca-viana-do-castelo",
  "vila-nova-de-cerveira": "vila-nova-de-cerveira-viana-do-castelo",
  caminha: "caminha-viana-do-castelo",
  "moledo-caminha": "moledo-caminha-viana-do-castelo",
  "vila-praia-de-ancora": "vila-praia-de-ancora-viana-do-castelo",
  "afife-carreco": "afife-viana-do-castelo",
  "viana-do-castelo": "viana-do-castelo-viana-do-castelo",
  "ponte-de-lima": "ponte-de-lima-viana-do-castelo",
  esposende: "esposende-braga",
  "povoa-de-varzim": "povoa-de-varzim-porto",
  "vila-do-conde": "vila-do-conde-porto",
};

const ZONA_PATH: Record<string, string> = {
  "baixo-mino": "pontevedra/baixo-mino",
  "val-minor": "pontevedra/val-minor",
  "vigo-e-ria": "pontevedra/vigo-comarca",
  "o-morrazo": "pontevedra/o-morrazo",
  "pontevedra-e-sanxenxo": "pontevedra/pontevedra-provincia",
  "o-salnes": "pontevedra/o-salnes",
  "barbanza-e-noia": "a-coruna/barbanza",
  "golfo-artabro-e-ferrol": "a-coruna/a-coruna-provincia",
  "a-marina": "lugo/a-marina",
  "asturias-occidente": "asturias/occidente",
  "asturias-centro": "asturias/centro",
  "asturias-oriente": "asturias/oriente",
  "cantabria-occidental": "cantabria/cantabria",
  "cantabria-oriental": "cantabria/cantabria",
  "alto-minho": "viana-do-castelo-distrito",
  "litoral-norte": "porto-distrito",
};

export function urlIdealistaMunicipio(slug: string): string | null {
  const path = MUNICIPIO_PATH[slug];
  return path ? `${VENTA}/${path}/` : null;
}

export function urlIdealistaZona(zonaId: string): string | null {
  const path = ZONA_PATH[zonaId];
  return path ? `${VENTA}/${path}/` : null;
}
