/** Slugs con ficha publicada (promovidos desde NUEVO2). Ruta canónica: /{slug}/ */
export const NUEVO2_MUNICIPIO_SLUGS = new Set([
  "cudillero",
  "candas-carreno",
  "gijon",
  "soto-del-barco",
  "salinas-castrillon",
  "luanco-gozon",
  "muros-de-nalon",
  "oia",
  "o-rosal",
  "tomino",
  "a-guarda",
  "tui",
  "baiona",
  "nigran",
  "gondomar",
  "cangas",
  "moana",
  "bueu",
  "marin",
  "pontevedra",
  "poio",
  "sanxenxo",
  "o-grove",
  "vigo",
  "redondela",
  "soutomaior",
  "vilaboa",
  "meano",
  "cambados",
  "a-illa-de-arousa",
  "vilanova-de-arousa",
  "vilagarcia-de-arousa",
  "rianxo",
  "boiro",
  "a-pobra-do-caraminal",
  "ribeira",
  "porto-do-son",
  "noia",
  "oleiros",
  "a-coruna",
  "mino",
  "sada",
  "bergondo",
  "ares",
  "ferrol",
  "o-vicedo",
  "viveiro",
  "xove",
  "cervo",
  "burela",
  "foz",
  "barreiros",
  "ribadeo",
  "castropol",
  "tapia-de-casariego",
  "navia",
  "luarca-valdes",
  "villaviciosa",
  "colunga",
  "ribadesella",
  "llanes",
  "ribadedeva",
  "san-vicente-de-la-barquera",
  "comillas",
  "suances",
  "liencres-pielagos",
  "santander",
  "ribamontan-al-mar",
  "noja",
  "santona",
  "laredo",
  "castro-urdiales",
  "valenca",
  "vila-nova-de-cerveira",
  "caminha",
  "moledo-caminha",
  "vila-praia-de-ancora",
  "afife-carreco",
  "viana-do-castelo",
  "ponte-de-lima",
  "esposende",
  "povoa-de-varzim",
  "vila-do-conde",
]);

/** Alias histórico del set de fichas NUEVO2. */
export const FICHAS_PUBLICADAS_SLUGS = NUEVO2_MUNICIPIO_SLUGS;

/** Enlace canónico a ficha de municipio. */
export function hrefFichaMunicipio(_zonaId: string, slug: string): string {
  return `/${slug}/`;
}
